### ISSUE TITLE
Output issues

### ISSUE THREAD

**Issue by thomasareed** [santoru/filewatcher#5]
A couple issues with the output:

1) There can be a lot of "Detected N/A event" lines in the output.

2) The program appears to exit by itself after a short amount of time. I'm unclear on whether it's encountering an error or if this is purposeful.

**Comment by delahaya** [comment]
I second this.

**Comment by ghost** [comment]
Hi, thanks for your comment.
1. I still didn't indexed these events. I'm trying to find a nice way to do it automatically. I'm actually working on it, I hope I will be able to fix it in a couple of days.
2. I found the program terminating because of a segmentation fault sometimes, I'm working on it.

**Comment by ghost** [comment]
@thomasareed I pushed the update that parse also the other events, with commit 0f4122b0efa1312c7bee82588c60a9a92316b915. Now you should see them correctly. Maybe I also found the reason about the segmentation fault. It seems working for now.
